[2025-03-09T15:00:02.380+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T15:00:02.391+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_fire_incidents_dag.testing_data scheduled__2025-03-09T12:00:00+00:00 [queued]>
[2025-03-09T15:00:02.396+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_fire_incidents_dag.testing_data scheduled__2025-03-09T12:00:00+00:00 [queued]>
[2025-03-09T15:00:02.397+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-09T15:00:02.406+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): testing_data> on 2025-03-09 12:00:00+00:00
[2025-03-09T15:00:02.410+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=17069) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T15:00:02.411+0000] {standard_task_runner.py:72} INFO - Started process 17071 to run task
[2025-03-09T15:00:02.412+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_fire_incidents_dag', 'testing_data', 'scheduled__2025-03-09T12:00:00+00:00', '--job-id', '496', '--raw', '--subdir', 'DAGS_FOLDER/fire_incidents_dag.py', '--cfg-path', '/tmp/tmphfojqddz']
[2025-03-09T15:00:02.413+0000] {standard_task_runner.py:105} INFO - Job 496: Subtask testing_data
[2025-03-09T15:00:02.446+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_fire_incidents_dag.testing_data scheduled__2025-03-09T12:00:00+00:00 [running]> on host fad361e322ea
[2025-03-09T15:00:02.502+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_fire_incidents_dag' AIRFLOW_CTX_TASK_ID='testing_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T12:00:00+00:00'
[2025-03-09T15:00:02.503+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T15:00:02.503+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T15:00:02.504+0000] {logging_mixin.py:190} INFO - Current task name:testing_data state:running start_date:2025-03-09 15:00:02.392116+00:00
[2025-03-09T15:00:02.504+0000] {logging_mixin.py:190} INFO - Dag name:etl_fire_incidents_dag and current dag run status:running
[2025-03-09T15:00:02.504+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T15:00:02.516+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-09T15:00:02.525+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T15:00:02.526+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_fire_incidents_dag, task_id=testing_data, run_id=scheduled__2025-03-09T12:00:00+00:00, execution_date=20250309T120000, start_date=20250309T150002, end_date=20250309T150002
[2025-03-09T15:00:02.543+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-09T15:00:02.543+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-09T15:00:02.543+0000] {logging_mixin.py:190} INFO - Dag name:etl_fire_incidents_dag queued_at:2025-03-09 15:00:01.024270+00:00
[2025-03-09T15:00:02.543+0000] {logging_mixin.py:190} INFO - Task hostname:fad361e322ea operator:PythonOperator
[2025-03-09T15:00:02.585+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-09T15:00:02.601+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T15:00:02.605+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
