[2025-03-10T21:09:27.136+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T21:09:27.320+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_nyc_fire_incidents_dag.transform_data_task manual__2025-03-10T21:09:05.966501+00:00 [queued]>
[2025-03-10T21:09:27.329+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_nyc_fire_incidents_dag.transform_data_task manual__2025-03-10T21:09:05.966501+00:00 [queued]>
[2025-03-10T21:09:27.330+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-10T21:09:27.344+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_data_task> on 2025-03-10 21:09:05.966501+00:00
[2025-03-10T21:09:27.351+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=148) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T21:09:27.353+0000] {standard_task_runner.py:72} INFO - Started process 150 to run task
[2025-03-10T21:09:27.354+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_nyc_fire_incidents_dag', 'transform_data_task', 'manual__2025-03-10T21:09:05.966501+00:00', '--job-id', '621', '--raw', '--subdir', 'DAGS_FOLDER/fire_incidents_dag.py', '--cfg-path', '/tmp/tmp83ev28op']
[2025-03-10T21:09:27.355+0000] {standard_task_runner.py:105} INFO - Job 621: Subtask transform_data_task
[2025-03-10T21:09:27.398+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_nyc_fire_incidents_dag.transform_data_task manual__2025-03-10T21:09:05.966501+00:00 [running]> on host 544a43034a42
[2025-03-10T21:09:27.484+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_nyc_fire_incidents_dag' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T21:09:05.966501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T21:09:05.966501+00:00'
[2025-03-10T21:09:27.485+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T21:09:27.486+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T21:09:27.486+0000] {logging_mixin.py:190} INFO - Current task name:transform_data_task state:running start_date:2025-03-10 21:09:27.320828+00:00
[2025-03-10T21:09:27.486+0000] {logging_mixin.py:190} INFO - Dag name:etl_nyc_fire_incidents_dag and current dag run status:running
[2025-03-10T21:09:27.487+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T21:09:27.487+0000] {logging_mixin.py:190} INFO - Pulling xcom!!!!!
[2025-03-10T21:09:27.634+0000] {warnings.py:112} WARNING - /opt/***/dags/pull_fire_incidents.py:48: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(transform_json_data)

[2025-03-10T21:09:27.827+0000] {logging_mixin.py:190} INFO - Transforming NYC Fire Incidents Data....
[2025-03-10T21:09:27.847+0000] {logging_mixin.py:190} INFO - Transformations are Complete
[2025-03-10T21:09:28.220+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-10T21:09:28.231+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T21:09:28.231+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_nyc_fire_incidents_dag, task_id=transform_data_task, run_id=manual__2025-03-10T21:09:05.966501+00:00, execution_date=20250310T210905, start_date=20250310T210927, end_date=20250310T210928
[2025-03-10T21:09:28.255+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-10T21:09:28.255+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-10T21:09:28.255+0000] {logging_mixin.py:190} INFO - Dag name:etl_nyc_fire_incidents_dag queued_at:2025-03-10 21:09:05.990390+00:00
[2025-03-10T21:09:28.256+0000] {logging_mixin.py:190} INFO - Task hostname:544a43034a42 operator:PythonOperator
[2025-03-10T21:09:28.291+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T21:09:28.313+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T21:09:28.315+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
